services:
  redis_db:
    image: docker.io/library/redis
    container_name: redis_db
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_volume:/data

  multi-container-deploy-backend:
    image: docker.io/danggro/multi-container-deploy-test-backend:latest
    container_name: multi-container-deploy-backend
    environment:
      POSTGRES_DB: postgres://postgres:Danggro@120300@mcdt.postgres.database.azure.com:5432/test
      REDIS_DB: redis://redis_db:6379
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_started

  multi-container-deploy-frontend:
    image: docker.io/danggro/multi-container-deploy-test-frontend:latest
    container_name: multi-container-deploy-frontend
    depends_on:
      multi-container-deploy-backend:
        condition: service_started

  nginx:
    image: docker.io/danggro/mcdt-nginx:latest
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      multi-container-deploy-frontend:
        condition: service_started
      multi-container-deploy-backend:
        condition: service_started

volumes:
  redis_volume:
