services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: secret
      PGUSER: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_volume:/var/lib/postgresql/data

  redis_db:
    image: redis
    container_name: redis_db
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_volume:/data

  multi-container-deploy-backend:
    image: multi-container-deploy-backend
    container_name: multi-container-deploy-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres://postgres:secret@postgres_db:5432/test
      REDIS_DB: redis://redis_db:6379
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  pg_volume:
  redis_volume:
