name: Build, Tag, & Push Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            frontend
            backend

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build MCDT Frontend Image
      #   run: docker build ./frontend -t danggro/multi-container-deploy-test-frontend:latest

      # - name: Build MCDT Backend Image
      #   run: docker build ./backend -t danggro/multi-container-deploy-test-backend:latest

      # - name: Build MCDT Nginx Image
      #   run: docker build ./nginx -t danggro/mcdt-nginx:latest

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        id: bumb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "frontend"
        with:
          skip-tag: "true"
          skip-commit: "true"
          skip-push: "true"

      - name: bump npm version
        env:
          NEW_TAG: ${{ steps.bump.outputs.newTag }}
        run: |
          cd frontend
          npm version $NEW_TAG
          git checkout -b $NEW_TAG
          git commit -am "Update to $NEW_TAG (2)"
          git push origin $NEW_TAG -f

      # git push -f origin main
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "#patch"
          REPO_OWNER: danggro

      # - name: Push MCDT Frontend Image
      #   run: docker push danggro/multi-container-deploy-test-frontend:latest

      # - name: Push MCDT Backend Image
      #   run: docker push danggro/multi-container-deploy-test-backend:latest

      # - name: Push MCDT Nginx Image
      #   run: docker push danggro/mcdt-nginx:latest
