name: Publish Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) Backend
        id: backend
        uses: docker/metadata-action@v5
        with:
          images: danggro/multi-container-deploy-test-backend

      - name: Build and push Docker Image Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ steps.backend.outputs.tags }}
          labels: ${{ steps.backend.outputs.labels }}

      - name: Extract metadata (tags, labels) Frontend
        id: frontend
        uses: docker/metadata-action@v5
        with:
          images: danggro/multi-container-deploy-test-frontend

      - name: Build and push Docker Image Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: ${{ steps.frontend.outputs.tags }}
          labels: ${{ steps.frontend.outputs.labels }}

  # - name: Build and push Docker Image Nginx
  #   uses: docker/build-push-action@v5
  #   with:
  #     context: ./nginx/
  #     push: true

  tag-release:
    name: Versioning
    needs: [push_to_registry]
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          REPO_OWNER: danggro
